CREATE TABLE IF NOT EXISTS processed_event
(
    event_id     VARCHAR(100) PRIMARY KEY,
    event_type   VARCHAR(100)             NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);