CREATE TABLE inventory_stock
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    part_id            BIGINT                                  NOT NULL,
    available_quantity BIGINT                                  NOT NULL,
    reserved_quantity  BIGINT                                  NOT NULL,
    minimum_quantity   BIGINT                                  NOT NULL,
    maximum_quantity   BIGINT                                  NOT NULL,
    CONSTRAINT pk_inventory_stock PRIMARY KEY (id),

    CONSTRAINT chk_inventory_stock_available
        CHECK (available_quantity >= 0),

    CONSTRAINT chk_inventory_stock_minimum_maximum
        CHECK (minimum_quantity <= maximum_quantity),

    CONSTRAINT chk_inventory_stock_reserved
        CHECK (reserved_quantity >= 0),

    CONSTRAINT chk_inventory_stock_minimum
        CHECK (minimum_quantity >= 0),

    CONSTRAINT chk_inventory_stock_maximum
        CHECK (maximum_quantity >= 0)
);

ALTER TABLE inventory_stock
    ADD CONSTRAINT uk_inventory_stock_part_id UNIQUE (part_id);

-- DROP TABLE flyway_bootstrap CASCADE; this was automatically added???