DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='parts' AND column_name='name') THEN
ALTER TABLE parts RENAME COLUMN name TO part_name;
END IF;
END $$;

ALTER TABLE parts ADD COLUMN IF NOT EXISTS unit_of_measure VARCHAR(20) NOT NULL DEFAULT 'PCS';

ALTER TABLE parts ADD COLUMN IF NOT EXISTS part_id VARCHAR(50);
ALTER TABLE parts ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE parts SET part_id = part_code WHERE part_id IS NULL;
ALTER TABLE parts ALTER COLUMN part_id SET NOT NULL;
ALTER TABLE parts ADD CONSTRAINT uk_parts_part_id UNIQUE (part_id);