CREATE TABLE vehicle_timeline
(
    timeline_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_id      VARCHAR(255)                            NOT NULL,
    event_id        VARCHAR(255)                            NOT NULL,
    event_type      VARCHAR(255)                            NOT NULL,
    source_service  VARCHAR(255),
    event_timestamp TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vehicle_timeline PRIMARY KEY (timeline_id),
    CONSTRAINT uc_vehicle_timeline_event UNIQUE (event_id)
);

