INSERT INTO node (node_id, name, type, created_date)
VALUES ('WAREHOUSE-A', 'Main Warehouse A', 'WAREHOUSE', CURRENT_TIMESTAMP),
       ('WAREHOUSE-B', 'Secondary Warehouse B', 'WAREHOUSE', CURRENT_TIMESTAMP),
       ('JUNCTION-1', 'Central Junction 1', 'JUNCTION', CURRENT_TIMESTAMP),
       ('JUNCTION-2', 'Central Junction 2', 'JUNCTION', CURRENT_TIMESTAMP),
       ('JUNCTION-3', 'Routing Junction 3', 'JUNCTION', CURRENT_TIMESTAMP),
       ('BUFFER-A', 'Buffer Zone A', 'BUFFER', CURRENT_TIMESTAMP),
       ('BUFFER-B', 'Buffer Zone B', 'BUFFER', CURRENT_TIMESTAMP),
       ('LINE-2-BODY-STATION', 'Line 2 Body Station', 'LINE_STATION', CURRENT_TIMESTAMP),
       ('LINE-2-PAINT-STATION', 'Line 2 Paint Station', 'LINE_STATION', CURRENT_TIMESTAMP),
       ('LINE-2-POWERTRAIN-STATION', 'Line 2 Powertrain Station', 'LINE_STATION', CURRENT_TIMESTAMP),
       ('QUALITY-AREA', 'Quality Inspection Area', 'QUALITY_AREA', CURRENT_TIMESTAMP);
INSERT INTO edge (edge_id, source_node_id, target_node_id, distance_meters, created_date)
VALUES ('EDGE-001', 'WAREHOUSE-A', 'JUNCTION-1', 15, CURRENT_TIMESTAMP),
       ('EDGE-002', 'WAREHOUSE-A', 'JUNCTION-2', 18, CURRENT_TIMESTAMP),
       ('EDGE-003', 'WAREHOUSE-B', 'JUNCTION-2', 10, CURRENT_TIMESTAMP),
       ('EDGE-004', 'JUNCTION-1', 'BUFFER-A', 12, CURRENT_TIMESTAMP),
       ('EDGE-005', 'JUNCTION-1', 'BUFFER-B', 20, CURRENT_TIMESTAMP),
       ('EDGE-006', 'JUNCTION-2', 'BUFFER-B', 14, CURRENT_TIMESTAMP),
       ('EDGE-007', 'JUNCTION-2', 'JUNCTION-3', 16, CURRENT_TIMESTAMP),
       ('EDGE-008', 'BUFFER-A', 'LINE-2-BODY-STATION', 10, CURRENT_TIMESTAMP),
       ('EDGE-009', 'BUFFER-B', 'LINE-2-PAINT-STATION', 22, CURRENT_TIMESTAMP),
       ('EDGE-010', 'JUNCTION-3', 'LINE-2-PAINT-STATION', 12, CURRENT_TIMESTAMP),
       ('EDGE-011', 'JUNCTION-3', 'LINE-2-POWERTRAIN-STATION', 15, CURRENT_TIMESTAMP),
       ('EDGE-012', 'LINE-2-BODY-STATION', 'JUNCTION-3', 17, CURRENT_TIMESTAMP),
       ('EDGE-013', 'LINE-2-PAINT-STATION', 'QUALITY-AREA', 40, CURRENT_TIMESTAMP),
       ('EDGE-014', 'LINE-2-POWERTRAIN-STATION', 'QUALITY-AREA', 25, CURRENT_TIMESTAMP);
INSERT INTO agv (agv_id, status, current_node_id, battery_level, created_date, last_updated)
VALUES ('AGV-001', 'AVAILABLE', 'WAREHOUSE-A', 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('AGV-002', 'AVAILABLE', 'JUNCTION-1', 85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('AGV-003', 'AVAILABLE', 'WAREHOUSE-B', 91, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);